name: Tests

on:
  push:
      branches:
        - 'master'
      tags:
        - v1.**

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # See https://github.com/actions/runner-images#available-images
        os: [ubuntu-latest]
        python-version: ['3.8', '3.10', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: true

    - name: Install dependencies
      run: |
        pdm install

    - name: Test with tox
      run: |
        pdm tox